# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devbrain < Formula
  desc "Turn your prompts into a durable, queryable brain any agent can resume from"
  homepage "https://github.com/TheWeiHu/devbrain"
  version "1.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TheWeiHu/devbrain/releases/download/v1.4.1/devbrain_1.4.1_darwin_amd64.tar.gz"
      sha256 "b1879cb7f9c741d0311554dd72e44801fff68ccac21e69c30c2b646c55e3a85c"

      define_method(:install) do
        bin.install "devbrain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TheWeiHu/devbrain/releases/download/v1.4.1/devbrain_1.4.1_darwin_arm64.tar.gz"
      sha256 "126b28be8885868f2429a99d1ea272e99fd39f9886632d49011b464ba458fed3"

      define_method(:install) do
        bin.install "devbrain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheWeiHu/devbrain/releases/download/v1.4.1/devbrain_1.4.1_linux_amd64.tar.gz"
      sha256 "578f2253ff7c1721dd8c3ecf78ae7984d0002cde73bddda5ebfe25a0d950e0ba"
      define_method(:install) do
        bin.install "devbrain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheWeiHu/devbrain/releases/download/v1.4.1/devbrain_1.4.1_linux_arm64.tar.gz"
      sha256 "04fa19033616b668599604be3a7fc3459500c52769cd083abf75680f6b42e1d9"
      define_method(:install) do
        bin.install "devbrain"
      end
    end
  end

  def caveats
    <<~EOS
      Wire this machine (hooks, skills, dashboard):
        devbrain install
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/devbrain version")
  end
end
