# typed: false
# frozen_string_literal: true

# This file was generated by devbrain's scripts/brew-formula-push.sh. DO NOT EDIT.
class Devbrain < Formula
  desc "Turn your prompts into a durable, queryable brain any agent can resume from"
  homepage "https://github.com/TheWeiHu/devbrain"
  version "1.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TheWeiHu/devbrain/releases/download/v1.5.2/devbrain_1.5.2_darwin_amd64.tar.gz"
      sha256 "dd2334e476ff7844dae04181400b4a1822b384f27606400aa896b2a644158285"

      define_method(:install) do
        bin.install "devbrain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TheWeiHu/devbrain/releases/download/v1.5.2/devbrain_1.5.2_darwin_arm64.tar.gz"
      sha256 "4192a3cf404c8afcf40dbc5ab44eb64b9c176df41a85d3f04a7469a636160581"

      define_method(:install) do
        bin.install "devbrain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheWeiHu/devbrain/releases/download/v1.5.2/devbrain_1.5.2_linux_amd64.tar.gz"
      sha256 "f3c792d973b0e1c68561226802ef615a9e64c447fab49e3c9b55e811f0b86338"
      define_method(:install) do
        bin.install "devbrain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheWeiHu/devbrain/releases/download/v1.5.2/devbrain_1.5.2_linux_arm64.tar.gz"
      sha256 "5b8777e2fc2d0db0fe7baab7e8a29795b3941bd17de9ea20c52f0467b8bbeeed"
      define_method(:install) do
        bin.install "devbrain"
      end
    end
  end

  def caveats
    <<~EOS
      Wire this machine (hooks, skills, dashboard):
        devbrain install
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/devbrain version")
  end
end
